# Generated by Django 3.0.2 on 2020-01-29 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0005_auto_20200128_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Inicio')),
                ('end', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fim')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='veiculos.Vehicle')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
