# Generated by Django 3.0.2 on 2020-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='state',
            field=models.CharField(choices=[('provisoria', 'Provisória'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='provisoria', max_length=10, verbose_name='Estado da Reserva'),
        ),
    ]
