# Generated by Django 3.0.2 on 2020-01-28 17:44

from django.db import migrations, models
import dynamicfleet.veiculos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[dynamicfleet.veiculos.validators.validate_year], verbose_name='Ano'),
        ),
    ]
