# Generated by Django 3.0.2 on 2020-01-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='state',
        ),
    ]
