# Generated by Django 3.0.2 on 2020-01-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_remove_vehicle_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Manutenção')], default='disponivel', max_length=10, verbose_name='Estado'),
        ),
    ]
